import { JourneyMemory, JourneyChapter, OccasionThemeConfig } from './types';
import { OccasionType } from '../../../types';

export const JOURNEY_CHAPTERS: JourneyChapter[] = [
  {
    id: 1,
    title: 'Chapter I: The Early Spark',
    subtitle: 'Where laughter began and roots grew deep',
    roadProgress: 8,
    icon: '🌱',
  },
  {
    id: 2,
    title: 'Chapter II: Sunlit Adventures',
    subtitle: 'Wanderlust, unplanned roads, and unforgettable nights',
    roadProgress: 32,
    icon: '🧭',
  },
  {
    id: 3,
    title: 'Chapter III: Pillars of Grace',
    subtitle: 'Words of wisdom, milestones, and shared warmth',
    roadProgress: 58,
    icon: '✨',
  },
  {
    id: 4,
    title: 'Chapter IV: The Horizon Ahead',
    subtitle: 'Honoring who you are and everything still to come',
    roadProgress: 82,
    icon: '🌟',
  },
];

export const OCCASION_THEMES: Record<OccasionType, OccasionThemeConfig> = {
  Birthday: {
    occasionType: 'Birthday',
    personName: 'Sarah Jenkins',
    title: "Sarah's 25th Birthday Journey",
    subtitle: 'Little moments. Beautiful memories. A quarter-century of joy.',
    instruction: 'Explore the journey to discover your memories',
    destinationTitle: '25 Years of Pure Radiance',
    destinationQuote: 'The road doesn’t end here — this is just the beginning of your greatest chapter yet.',
    startArchLabel: 'Where the Story Begins',
    accentColor: '#FF6B6B',
    ambientGradient: 'from-amber-50 via-rose-50/50 to-orange-50/30',
    roadPalette: {
      surface: 'url(#roadCobblestoneWarm)',
      border: '#E29578',
      centerDash: '#FFDDD2',
      curbGlow: 'rgba(255, 107, 107, 0.25)',
    },
    hillsPalette: {
      back: '#F7EDE2',
      mid: '#F5CAC3',
      front: '#E8D5B5',
    },
  },
  Anniversary: {
    occasionType: 'Anniversary',
    personName: 'Elena & Marcus',
    title: 'Elena & Marcus: Our Journey Together',
    subtitle: 'Three decades of shared love, quiet morning coffees, and wild dreams.',
    instruction: 'Walk down memory lane and rediscover 30 years of devotion',
    destinationTitle: '30 Golden Years & Ever After',
    destinationQuote: 'Two wandering souls, one winding road, and a love that only grows deeper with time.',
    startArchLabel: 'The Day It All Began • 1997',
    accentColor: '#D4AF37',
    ambientGradient: 'from-amber-50 via-yellow-50/40 to-stone-50',
    roadPalette: {
      surface: 'url(#roadCobblestoneGold)',
      border: '#C5A059',
      centerDash: '#F3E5AB',
      curbGlow: 'rgba(212, 175, 55, 0.3)',
    },
    hillsPalette: {
      back: '#EFE6DD',
      mid: '#E2D4C3',
      front: '#D9C5B2',
    },
  },
  Wedding: {
    occasionType: 'Wedding',
    personName: 'Clara & James',
    title: 'Clara & James: Our Beautiful Journey',
    subtitle: 'From a chance encounter in Paris to standing side by side forever.',
    instruction: 'Follow the winding path of vows, blessings, and lifelong promises',
    destinationTitle: 'United in Love & Joy',
    destinationQuote: 'May your road always be lined with laughter, warmth, and hands held tight.',
    startArchLabel: 'Chapter One: Two Paths Meet',
    accentColor: '#6B8E7D',
    ambientGradient: 'from-emerald-50/60 via-stone-50 to-teal-50/30',
    roadPalette: {
      surface: 'url(#roadCobblestoneSage)',
      border: '#8FBC8F',
      centerDash: '#E0EEE0',
      curbGlow: 'rgba(107, 142, 125, 0.25)',
    },
    hillsPalette: {
      back: '#E2EBE4',
      mid: '#D1DFD5',
      front: '#C3D4C8',
    },
  },
  'Bride to Be': {
    occasionType: 'Bride to Be',
    personName: 'Clara Hughes',
    title: "Clara's Bridal Journey",
    subtitle: 'Celebrating the bride-to-be with secrets, cheers, and timeless memories.',
    instruction: 'Step through the moments leading up to the unforgettable "I Do"',
    destinationTitle: 'Here Comes the Bride! 💍',
    destinationQuote: 'Surrounded by the women who love you most, stepping into your sweetest forever.',
    startArchLabel: 'To the Bride We Adore',
    accentColor: '#E07A5F',
    ambientGradient: 'from-rose-50 via-pink-50/40 to-purple-50/20',
    roadPalette: {
      surface: 'url(#roadCobblestoneRose)',
      border: '#DDA15E',
      centerDash: '#FFE8D6',
      curbGlow: 'rgba(224, 122, 95, 0.25)',
    },
    hillsPalette: {
      back: '#F4ECE1',
      mid: '#EAD7C5',
      front: '#DFCCA9',
    },
  },
  Graduation: {
    occasionType: 'Graduation',
    personName: 'Alex Rivera',
    title: 'Alex: Journey to This Moment',
    subtitle: 'Late night study sessions, coffee-fueled grit, and triumphant celebrations.',
    instruction: 'Explore the milestones and memories that built this achievement',
    destinationTitle: 'A Triumphant Horizon Reached',
    destinationQuote: 'The world is wide open before you. Step boldly onto your next great path.',
    startArchLabel: 'First Day on Campus',
    accentColor: '#2B5B84',
    ambientGradient: 'from-sky-50 via-indigo-50/30 to-blue-50/20',
    roadPalette: {
      surface: 'url(#roadCobblestoneNavy)',
      border: '#4682B4',
      centerDash: '#B0E0E6',
      curbGlow: 'rgba(43, 91, 132, 0.25)',
    },
    hillsPalette: {
      back: '#DEE7EE',
      mid: '#CBD8E2',
      front: '#B5C8D5',
    },
  },
  Other: {
    occasionType: 'Other',
    personName: 'Honored Friend',
    title: 'The Unforgettable Memory Journey',
    subtitle: 'Cherished memories gathered with love and celebration.',
    instruction: 'Explore the journey to discover each special moment',
    destinationTitle: 'A Celebration of You',
    destinationQuote: 'Every step of this road reflects the light and joy you bring to all of us.',
    startArchLabel: 'Where Memories Live',
    accentColor: '#FF6B6B',
    ambientGradient: 'from-amber-50 via-rose-50/50 to-orange-50/30',
    roadPalette: {
      surface: 'url(#roadCobblestoneWarm)',
      border: '#E29578',
      centerDash: '#FFDDD2',
      curbGlow: 'rgba(255, 107, 107, 0.25)',
    },
    hillsPalette: {
      back: '#F7EDE2',
      mid: '#F5CAC3',
      front: '#E8D5B5',
    },
  },
};

export const OCCASION_MEMORIES: Record<OccasionType, JourneyMemory[]> = {
  Birthday: [
    {
      id: 'jm-b1',
      title: 'Our Sunrise Hike in Amalfi Cliffs',
      contributorName: 'Emma Watson',
      contributorRole: 'Best Friend since 2018',
      contributorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Remember waking up at 5am just to catch the golden light over the Amalfi cliffs? You were complaining the whole climb, but the second the sun broke through, your smile lit up the Mediterranean. Happy 25th birthday, my soul sister! ❤️',
      mediaUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=80',
      date: 'June 2024',
      likesCount: 18,
      styleVariant: 'polaroid',
      side: 'left',
      roadProgress: 14,
      xOffsetPercent: -6,
      chapter: 1,
      locationTag: 'Amalfi Coast, Italy',
      accentQuote: '“The sunrise was breathtaking, but watching your awe was the real magic.”',
    },
    {
      id: 'jm-b2',
      title: 'Studio Birthday Acoustic Serenade',
      contributorName: 'Daniel Vance',
      contributorRole: 'Brother & Musician',
      contributorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      type: 'audio',
      duration: '0:48',
      content:
        'Recorded this acoustic version of your favorite Beatles track straight from the studio! Sarah, you have been my biggest inspiration through college, heartbreaks, and dream-chasing. Turn up the volume for 48 seconds of love!',
      mediaUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80',
      date: 'May 2025',
      likesCount: 24,
      styleVariant: 'circular-landmark',
      side: 'right',
      roadProgress: 22,
      xOffsetPercent: 7,
      chapter: 1,
      locationTag: 'Abbey Studio 4',
      accentQuote: '“Hit play for an acoustic serenade recorded just for Sarah.”',
    },
    {
      id: 'jm-b3',
      title: 'Midnight Matcha in Shibuya',
      contributorName: 'Lucas Grey',
      contributorRole: 'Travel Buddy',
      contributorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      type: 'video',
      duration: '1:42',
      content:
        'We got completely lost in Shibuya alleyways looking for authentic green tea soft serve at 1 AM. Watch till the end when you tried to speak Japanese to the robotic vending machine and made the whole train station laugh!',
      mediaUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1000&q=80',
      date: 'October 2024',
      likesCount: 29,
      styleVariant: 'floating-glass',
      side: 'left',
      roadProgress: 38,
      xOffsetPercent: -8,
      chapter: 2,
      locationTag: 'Tokyo, Japan',
      accentQuote: '“Getting lost with you is ten times better than having a map.”',
    },
    {
      id: 'jm-b4',
      title: 'To 25 Years of Pure Grace',
      contributorName: 'Michael Chen',
      contributorRole: 'Design Co-Founder',
      contributorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80',
      type: 'wish',
      content:
        'Sarah, you make everyone in your orbit feel heard, valued, and capable of big things. Wishing you a year overflowing with bold creative risks, slow sunny Sunday mornings, and matcha that tastes like pure heaven. Happy quarter-century!',
      date: 'Yesterday',
      likesCount: 15,
      styleVariant: 'gilded-frame',
      side: 'right',
      roadProgress: 44,
      xOffsetPercent: 5,
      chapter: 2,
      locationTag: 'Brooklyn Atelier',
      accentQuote: '“You make every room softer and every dream bigger.”',
    },
    {
      id: 'jm-b5',
      title: 'College Graduation Rooftop Night',
      contributorName: 'Sophie & Liam',
      contributorRole: 'College Roommates',
      contributorAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Found this candid polaroid from graduation night! Remember when we made a pact that no matter where our careers pulled us in the world, we would fly in for each other’s big milestones? Here we are celebrating your 25th!',
      mediaUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=80',
      date: 'June 2023',
      likesCount: 21,
      styleVariant: 'polaroid',
      side: 'left',
      roadProgress: 52,
      xOffsetPercent: -5,
      chapter: 2,
      locationTag: 'West Village Rooftop',
      accentQuote: '“Degrees in hand, tears in our eyes, and a lifetime of sisterhood ahead.”',
    },
    {
      id: 'jm-b6',
      title: 'Sweet Blessings From Grandma Rose',
      contributorName: 'Grandma Rose',
      contributorRole: 'Grandmother',
      contributorAvatar: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?auto=format&fit=crop&w=150&q=80',
      type: 'audio',
      duration: '1:15',
      content:
        'My darling Sarah, watching you grow into this radiant, empathetic young woman has been the greatest joy of my twilight years. Never forget how much strength you carry in your tender heart. I love you to the stars and back.',
      mediaUrl: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1000&q=80',
      date: 'Last Week',
      likesCount: 42,
      styleVariant: 'memory-bubble',
      side: 'right',
      roadProgress: 64,
      xOffsetPercent: 8,
      chapter: 3,
      locationTag: 'Rosewood Cottage',
      accentQuote: '“Never forget how much strength you carry in your tender heart.”',
    },
    {
      id: 'jm-b7',
      title: 'Big Sur Highway 1 Convertible Cruise',
      contributorName: 'Chloe Taylor',
      contributorRole: 'Adventure Sister',
      contributorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Windows rolled down, Fleetwood Mac echoing across the Pacific coastline, sea salt in our hair, and laughing so hard our ribs ached. Big Sur was the moment we both realized 20s were going to be truly legendary.',
      mediaUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=1000&q=80',
      date: 'April 2024',
      likesCount: 19,
      styleVariant: 'scenic-milestone',
      side: 'left',
      roadProgress: 70,
      xOffsetPercent: -7,
      chapter: 3,
      locationTag: 'Big Sur, California',
      accentQuote: '“Salt air, loud music, and laughter that stopped time.”',
    },
    {
      id: 'jm-b8',
      title: 'The Surprise Puppy Reveal!',
      contributorName: 'David & Maya',
      contributorRole: 'Cousins',
      contributorAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80',
      type: 'video',
      duration: '0:58',
      content:
        'We secretly flew your golden retriever puppy Mochi into the garden party! Sarah’s jaw literally hit the grass. Rewatch her pure shock and happy tears right here.',
      mediaUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=1000&q=80',
      date: 'July 2024',
      likesCount: 37,
      styleVariant: 'circular-landmark',
      side: 'right',
      roadProgress: 76,
      xOffsetPercent: 6,
      chapter: 3,
      locationTag: 'Austin Back Lawn',
      accentQuote: '“Happy tears, wagging tails, and the best birthday surprise ever.”',
    },
    {
      id: 'jm-b9',
      title: 'A Letter Sealed With Infinite Love',
      contributorName: 'Mom & Dad',
      contributorRole: 'Proud Parents',
      contributorAvatar: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?auto=format&fit=crop&w=150&q=80',
      type: 'wish',
      content:
        'Twenty-five years ago today, you brought a brilliant warmth into our home that has never dimmed for a single second. Watching you build your dreams with kindness, grace, and courage fills our hearts beyond measure.',
      date: 'This Morning',
      likesCount: 34,
      styleVariant: 'gilded-frame',
      side: 'left',
      roadProgress: 86,
      xOffsetPercent: -6,
      chapter: 4,
      locationTag: 'Family Home',
      accentQuote: '“You brought a warmth into our world that has never dimmed.”',
    },
    {
      id: 'jm-b10',
      title: 'Golden Hour at the Botanical Glasshouse',
      contributorName: 'Oliver Vance',
      contributorRole: 'Little Brother',
      contributorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Snuck this photo of you while you were smelling the jasmine blooms in the conservatory. You looked like you stepped right out of an impressionist painting. You deserve all the good things coming your way, Sarah!',
      mediaUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1000&q=80',
      date: 'March 2025',
      likesCount: 17,
      styleVariant: 'floating-glass',
      side: 'right',
      roadProgress: 90,
      xOffsetPercent: 7,
      chapter: 4,
      locationTag: 'Kew Conservatory',
      accentQuote: '“Golden light through old glass, finding beauty everywhere you look.”',
    },
    {
      id: 'jm-b11',
      title: 'Late Night Acoustic Campfire Harmonies',
      contributorName: 'Hannah & Noah',
      contributorRole: 'Music Trio',
      contributorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
      type: 'audio',
      duration: '1:02',
      content:
        'Recorded around the pine embers under a canopy of stars. We sang three-part harmonies until our voices gave out. Listen close to hear the crackle of wood and Sarah laughing in the chorus.',
      mediaUrl: 'https://images.unsplash.com/photo-1478147427282-58a87a120781?auto=format&fit=crop&w=1000&q=80',
      date: 'August 2025',
      likesCount: 26,
      styleVariant: 'memory-bubble',
      side: 'left',
      roadProgress: 94,
      xOffsetPercent: -5,
      chapter: 4,
      locationTag: 'Lake Tahoe Shores',
      accentQuote: '“Stars above, embers glowing, and music that bound us together.”',
    },
    {
      id: 'jm-b12',
      title: 'Cheers to 25 and Beyond!',
      contributorName: 'The Whole Crew (12 Friends)',
      contributorRole: 'The Inner Circle',
      contributorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'All 12 of us gathered to raise a glass to you! May your 25th trip around the sun be your most dazzling, adventurous, and loving yet. We love you Sarah!',
      mediaUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1000&q=80',
      date: 'Tonight',
      likesCount: 50,
      styleVariant: 'scenic-milestone',
      side: 'right',
      roadProgress: 97,
      xOffsetPercent: 5,
      chapter: 4,
      locationTag: 'Celebration Terrace',
      accentQuote: '“Here’s to Sarah: the brightest heart in every room!”',
    },
  ],

  Anniversary: [
    {
      id: 'jm-a1',
      title: 'The Rainy Paris Cafe Where We Met',
      contributorName: 'Marcus',
      contributorRole: 'Husband & Partner',
      contributorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Thirty years ago, an afternoon downpour forced us both under the red awning of Café de Flore. You dropped your book, I picked up page 42, and neither of us ever looked away. Happy 30th anniversary, my heart.',
      mediaUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=80',
      date: 'Autumn 1995',
      likesCount: 31,
      styleVariant: 'polaroid',
      side: 'left',
      roadProgress: 14,
      xOffsetPercent: -6,
      chapter: 1,
      locationTag: 'Paris, France',
      accentQuote: '“The rain stopped, but our conversation never did.”',
    },
    {
      id: 'jm-a2',
      title: 'Our First Dance: Moon River',
      contributorName: 'Elena & Marcus',
      contributorRole: 'The Wedding Couple',
      contributorAvatar: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?auto=format&fit=crop&w=150&q=80',
      type: 'audio',
      duration: '1:10',
      content:
        'A remastered clip of our wedding orchestra playing Moon River on that candlelit September evening in 1997. Listen to Marcus whispering his vow right before the swell.',
      mediaUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80',
      date: 'September 1997',
      likesCount: 28,
      styleVariant: 'circular-landmark',
      side: 'right',
      roadProgress: 24,
      xOffsetPercent: 7,
      chapter: 1,
      locationTag: 'Villa Toscana',
      accentQuote: '“Two drifters off to see the world, there’s such a lot of world to see.”',
    },
    {
      id: 'jm-a3',
      title: 'Building Our First Home Together',
      contributorName: 'Claire (Daughter)',
      contributorRole: 'Eldest Daughter',
      contributorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Mom & Dad painting the nursery with roller brushes, both covered in buttercup yellow paint and smiling ear-to-ear. You taught us what unconditional partnership looks like.',
      mediaUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
      date: 'May 2002',
      likesCount: 22,
      styleVariant: 'gilded-frame',
      side: 'left',
      roadProgress: 36,
      xOffsetPercent: -7,
      chapter: 2,
      locationTag: 'Maple House',
      accentQuote: '“Brick by brick, song by song, they built a sanctuary for us.”',
    },
    {
      id: 'jm-a4',
      title: 'A Secret Toast for Mom & Dad',
      contributorName: 'Julian & Claire',
      contributorRole: 'Children',
      contributorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      type: 'video',
      duration: '2:15',
      content:
        'A surprise compilation of 30 family members around the world raising their glasses to 30 years of unwavering love. Grab tissues before you watch!',
      mediaUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1000&q=80',
      date: 'Last Week',
      likesCount: 45,
      styleVariant: 'floating-glass',
      side: 'right',
      roadProgress: 45,
      xOffsetPercent: 6,
      chapter: 2,
      locationTag: 'Global Family Tribute',
      accentQuote: '“30 years of teaching everyone around you what real devotion means.”',
    },
    {
      id: 'jm-a5',
      title: 'Venice Gondola at Twilight',
      contributorName: 'Elena',
      contributorRole: 'Wife',
      contributorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Our 15th anniversary in Venice. Marcus booked a gondola at sunset and pulled out a tiny handwritten poem he wrote on our first date. 30 years later, you still make my heart skip.',
      mediaUrl: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=1000&q=80',
      date: 'Autumn 2012',
      likesCount: 38,
      styleVariant: 'memory-bubble',
      side: 'left',
      roadProgress: 56,
      xOffsetPercent: -6,
      chapter: 3,
      locationTag: 'Grand Canal, Venice',
      accentQuote: '“Gilded water, ringing church bells, and you holding my hand.”',
    },
    {
      id: 'jm-a6',
      title: 'Grandkids Singing Anniversary Chorus',
      contributorName: 'Leo & Maya (Grandkids)',
      contributorRole: 'Grandchildren',
      contributorAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80',
      type: 'audio',
      duration: '0:52',
      content:
        'Grandpa and Grandma! We made up a special anniversary song with our toy ukulele. Happy 30 years! We love your warm blueberry pancakes and story nights!',
      mediaUrl: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1000&q=80',
      date: 'Yesterday',
      likesCount: 52,
      styleVariant: 'scenic-milestone',
      side: 'right',
      roadProgress: 66,
      xOffsetPercent: 7,
      chapter: 3,
      locationTag: 'Living Room',
      accentQuote: '“Ukulele chords and pure childlike joy for grandma & grandpa.”',
    },
    {
      id: 'jm-a7',
      title: 'Thirty Years of Laughing at Burned Roasts',
      contributorName: 'Uncle Roberto',
      contributorRole: 'Best Man 1997',
      contributorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80',
      type: 'wish',
      content:
        'Marcus, remember when Elena tried making your mom’s secret Osso Buco and set the fire alarm off? You ordered pizza and dined by candlelight on the kitchen floor. That is the secret to 30 years.',
      date: '3 days ago',
      likesCount: 29,
      styleVariant: 'polaroid',
      side: 'left',
      roadProgress: 74,
      xOffsetPercent: -5,
      chapter: 3,
      locationTag: 'Milano memories',
      accentQuote: '“Turning life’s smoke into candlelight and romance.”',
    },
    {
      id: 'jm-a8',
      title: 'The Golden Hour Olive Grove',
      contributorName: 'Elena & Marcus',
      contributorRole: 'Together Forever',
      contributorAvatar: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Walking between ancient olive trees planted over two centuries ago. Like these trees, our roots have grown so intertwined that we cannot tell where one begins and the other ends.',
      mediaUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=80',
      date: 'Summer 2025',
      likesCount: 41,
      styleVariant: 'gilded-frame',
      side: 'right',
      roadProgress: 82,
      xOffsetPercent: 6,
      chapter: 4,
      locationTag: 'Tuscany Grove',
      accentQuote: '“Two roots, one shade, timeless shelter against every storm.”',
    },
    {
      id: 'jm-a9',
      title: 'Vow Renewal Whispers',
      contributorName: 'Marcus',
      contributorRole: 'Husband',
      contributorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      type: 'audio',
      duration: '1:30',
      content:
        'A private recording of the vows Marcus read to Elena on their 30th anniversary morning by the seaside. The sweetest reaffirmation of love you will ever hear.',
      mediaUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1000&q=80',
      date: 'This Morning',
      likesCount: 46,
      styleVariant: 'circular-landmark',
      side: 'left',
      roadProgress: 88,
      xOffsetPercent: -6,
      chapter: 4,
      locationTag: 'Seaside Pavilion',
      accentQuote: '“I would choose you again in every lifetime, in every world.”',
    },
    {
      id: 'jm-a10',
      title: 'Our Family Tree in Full Bloom',
      contributorName: 'The Family',
      contributorRole: 'Generations',
      contributorAvatar: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Four generations gathered around Marcus and Elena for their golden portrait. Thirty years of love created this entire universe of laughter and warmth.',
      mediaUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1000&q=80',
      date: 'Yesterday',
      likesCount: 55,
      styleVariant: 'floating-glass',
      side: 'right',
      roadProgress: 92,
      xOffsetPercent: 7,
      chapter: 4,
      locationTag: 'Anniversary Banquet',
      accentQuote: '“Look at what 30 years of quiet devotion built.”',
    },
    {
      id: 'jm-a11',
      title: 'Thirty Years of Love Letters',
      contributorName: 'Elena',
      contributorRole: 'Wife',
      contributorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      type: 'wish',
      content:
        'To my dearest Marcus: Through every move, every sleepless night, every joy and every trial, you have been my lighthouse. Here is to our next thirty years together.',
      date: 'Today',
      likesCount: 39,
      styleVariant: 'memory-bubble',
      side: 'left',
      roadProgress: 95,
      xOffsetPercent: -5,
      chapter: 4,
      locationTag: 'Home Desk',
      accentQuote: '“You are the home I searched for my entire life.”',
    },
    {
      id: 'jm-a12',
      title: 'The Golden Pavilion Celebration',
      contributorName: 'Friends & Family Worldwide',
      contributorRole: 'Celebrants',
      contributorAvatar: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Glasses held high, sparklers dancing in the dusk, and 30 golden lanterns released into the midnight sky for Elena and Marcus. To thirty years and forever after!',
      mediaUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1000&q=80',
      date: 'Tonight',
      likesCount: 60,
      styleVariant: 'scenic-milestone',
      side: 'right',
      roadProgress: 98,
      xOffsetPercent: 5,
      chapter: 4,
      locationTag: 'Golden Pavilion',
      accentQuote: '“Lanterns in the night sky, carrying thirty years of wishes.”',
    },
  ],

  Wedding: [
    {
      id: 'jm-w1',
      title: 'The First Spark in Montmartre',
      contributorName: 'James (Groom)',
      contributorRole: 'Groom',
      contributorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Clara was holding an umbrella against the cobblestones, laughing at how the rain was washing away chalk drawings. That was the exact second I knew I would marry her.',
      mediaUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80',
      date: 'Spring 2021',
      likesCount: 32,
      styleVariant: 'polaroid',
      side: 'left',
      roadProgress: 14,
      xOffsetPercent: -6,
      chapter: 1,
      locationTag: 'Montmartre, Paris',
      accentQuote: '“Rain on the cobblestones, and the girl I knew was my forever.”',
    },
    {
      id: 'jm-w2',
      title: 'Our Vow Audio Recording Session',
      contributorName: 'Clara & James',
      contributorRole: 'Bride & Groom',
      contributorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
      type: 'audio',
      duration: '1:05',
      content:
        'Hear us reading our vows in whispered confidence the evening before the wedding in the secret cloister garden.',
      mediaUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1000&q=80',
      date: 'Yesterday',
      likesCount: 40,
      styleVariant: 'circular-landmark',
      side: 'right',
      roadProgress: 24,
      xOffsetPercent: 7,
      chapter: 1,
      locationTag: 'Cloister Garden',
      accentQuote: '“With this hand, I will lift your sorrows. Our road begins now.”',
    },
    {
      id: 'jm-w3',
      title: 'The Engagement on Cliffside Heights',
      contributorName: 'Maid of Honor Sarah',
      contributorRole: 'Maid of Honor',
      contributorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      type: 'video',
      duration: '1:34',
      content:
        'I hid behind the olive trees for two hours to capture James dropping to one knee! Clara gasped, dropped her sunhat, and tackled him to the grass before saying YES!',
      mediaUrl: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=1000&q=80',
      date: 'Summer 2024',
      likesCount: 47,
      styleVariant: 'floating-glass',
      side: 'left',
      roadProgress: 36,
      xOffsetPercent: -7,
      chapter: 2,
      locationTag: 'Santorini Cliffs',
      accentQuote: '“A dropped sunhat, a million tears, and the easiest YES on earth.”',
    },
    {
      id: 'jm-w4',
      title: 'A Father’s Blessing to the Couple',
      contributorName: 'Mr. Hughes',
      contributorRole: 'Father of the Bride',
      contributorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
      type: 'wish',
      content:
        'James, taking care of Clara’s heart is the highest honor. Seeing the devotion and gentle kindness in your eyes makes this the proudest day of my life. May you walk hand-in-hand through every season.',
      date: 'This Morning',
      likesCount: 35,
      styleVariant: 'gilded-frame',
      side: 'right',
      roadProgress: 46,
      xOffsetPercent: 6,
      chapter: 2,
      locationTag: 'Bridal Suite',
      accentQuote: '“Seeing how you cherish her makes this the happiest day of my life.”',
    },
    {
      id: 'jm-w5',
      title: 'The Wedding Dress First Look',
      contributorName: 'Bridesmaids Collective',
      contributorRole: 'Bridesmaids',
      contributorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'The collective gasp when Clara walked out in her silk veil! Pure poetry in motion. You are the most breathtaking bride the world has ever seen.',
      mediaUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1000&q=80',
      date: 'Today, 11:00 AM',
      likesCount: 38,
      styleVariant: 'polaroid',
      side: 'left',
      roadProgress: 56,
      xOffsetPercent: -6,
      chapter: 3,
      locationTag: 'Orangerie',
      accentQuote: '“Silk, lace, and a room full of weeping best friends.”',
    },
    {
      id: 'jm-w6',
      title: 'Groomsmen Acoustic Toast',
      contributorName: 'Groomsmen Band',
      contributorRole: 'Groomsmen',
      contributorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      type: 'audio',
      duration: '0:55',
      content:
        'A fun, heartfelt acoustic roast-and-toast written by the groomsmen the morning of the wedding, celebrating James winning Clara’s heart.',
      mediaUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80',
      date: 'Today, 1:30 PM',
      likesCount: 29,
      styleVariant: 'memory-bubble',
      side: 'right',
      roadProgress: 66,
      xOffsetPercent: 7,
      chapter: 3,
      locationTag: 'Banqueting Hall',
      accentQuote: '“He may have two left feet, but he has the biggest heart for Clara.”',
    },
    {
      id: 'jm-w7',
      title: 'The Walking Down the Aisle Moment',
      contributorName: 'Wedding Photographer',
      contributorRole: 'Visual Storyteller',
      contributorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Sunlight filtering through the cathedral stained glass, floral arches in full bloom, and James wiping away tears as Clara approached.',
      mediaUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80',
      date: 'Today, 2:15 PM',
      likesCount: 58,
      styleVariant: 'scenic-milestone',
      side: 'left',
      roadProgress: 75,
      xOffsetPercent: -6,
      chapter: 3,
      locationTag: 'Cathedral of Saint Claire',
      accentQuote: '“A thousand petals underfoot, two hearts beating as one.”',
    },
    {
      id: 'jm-w8',
      title: 'Vows Exchanged Under the Ancient Oak',
      contributorName: 'Officiant Bishop',
      contributorRole: 'Officiant',
      contributorAvatar: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?auto=format&fit=crop&w=150&q=80',
      type: 'wish',
      content:
        '“Love is patient, love is kind. It does not envy, it does not boast.” May your covenant remain as grounded as the roots of this oak and as boundless as the sky above.',
      date: 'Today, 3:00 PM',
      likesCount: 44,
      styleVariant: 'gilded-frame',
      side: 'right',
      roadProgress: 82,
      xOffsetPercent: 6,
      chapter: 4,
      locationTag: 'Under the Ancient Oak',
      accentQuote: '“Rooted in grace, flourishing under open skies.”',
    },
    {
      id: 'jm-w9',
      title: 'The Rose Petal Exit Shower',
      contributorName: 'All Guests',
      contributorRole: 'Wedding Guests',
      contributorAvatar: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=150&q=80',
      type: 'video',
      duration: '0:45',
      content:
        'Running through a tunnel of 100 cheering loved ones tossing fragrant white and blush rose petals into the air! Watch James spin Clara around in pure euphoria.',
      mediaUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=80',
      date: 'Today, 3:45 PM',
      likesCount: 52,
      styleVariant: 'circular-landmark',
      side: 'left',
      roadProgress: 88,
      xOffsetPercent: -6,
      chapter: 4,
      locationTag: 'Cathedral Courtyard',
      accentQuote: '“Blush petals flying, pure euphoria, husband and wife!”',
    },
    {
      id: 'jm-w10',
      title: 'Sunset Champagne Toast on the Terrace',
      contributorName: 'Catering Hostess',
      contributorRole: 'Celebration Host',
      contributorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Clinking vintage coupe glasses against a backdrop of lavender hills and golden sunset clouds. The first toast to Mr. & Mrs. Hughes!',
      mediaUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80',
      date: 'Tonight, 7:15 PM',
      likesCount: 39,
      styleVariant: 'floating-glass',
      side: 'right',
      roadProgress: 92,
      xOffsetPercent: 7,
      chapter: 4,
      locationTag: 'Lavender Terrace',
      accentQuote: '“Bubbles in the glass, twilight over the hills, happily ever after.”',
    },
    {
      id: 'jm-w11',
      title: 'First Dance Under the Fairylight Tent',
      contributorName: 'Wedding Band Singer',
      contributorRole: 'Live Performer',
      contributorAvatar: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=150&q=80',
      type: 'audio',
      duration: '1:45',
      content:
        'Live acoustic rendition of ‘Can’t Help Falling In Love’ as James and Clara spun beneath 10,000 warm fairy lights.',
      mediaUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1000&q=80',
      date: 'Tonight, 8:30 PM',
      likesCount: 61,
      styleVariant: 'memory-bubble',
      side: 'left',
      roadProgress: 95,
      xOffsetPercent: -5,
      chapter: 4,
      locationTag: 'Grand Pavilion',
      accentQuote: '“Like a river flows surely to the sea, darling so it goes.”',
    },
    {
      id: 'jm-w12',
      title: 'The Midnight Sparkler Send-Off',
      contributorName: 'Everyone',
      contributorRole: 'All Guests',
      contributorAvatar: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=150&q=80',
      type: 'photo',
      content:
        'Golden sparks lighting up the midnight air as the newlyweds waved goodbye from the vintage roadster. The road of marriage has officially begun!',
      mediaUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80',
      date: 'Tonight, Midnight',
      likesCount: 65,
      styleVariant: 'scenic-milestone',
      side: 'right',
      roadProgress: 98,
      xOffsetPercent: 5,
      chapter: 4,
      locationTag: 'Estate Gates',
      accentQuote: '“Golden sparks in the dark, heading into forever.”',
    },
  ],

  'Bride to Be': [],
  Graduation: [],
};

// Fill in Bride to Be and Graduation automatically using Birthday/Wedding as templates
OCCASION_MEMORIES['Bride to Be'] = OCCASION_MEMORIES.Wedding.map((m, idx) => ({
  ...m,
  id: `jm-btb-${idx + 1}`,
  title: m.title.replace('Wedding', 'Bridal').replace('Vow', 'Shower Message'),
}));

OCCASION_MEMORIES['Graduation'] = OCCASION_MEMORIES.Birthday.map((m, idx) => ({
  ...m,
  id: `jm-grad-${idx + 1}`,
  title: idx === 0 ? 'First Day on College Quad' : idx === 1 ? 'Dean’s Honor List Audio Note' : idx === 5 ? 'Professor Miller’s Graduation Recommendation' : m.title,
}));
