import { OccasionType } from '../../../types';
import { GardenMemory, GardenZoneInfo, OccasionGardenConfig } from './types';

export const GARDEN_ZONES: GardenZoneInfo[] = [
  {
    id: 'beginning',
    name: 'The Beginning',
    tagline: 'Where every delicate bud first took root',
    botanicalDescription: 'Early shared memories, tender beginnings, and the first roots of our bond.',
    accentColor: '#10B981', // Emerald green
  },
  {
    id: 'moments',
    name: 'Special Moments',
    tagline: 'Perennial blooms of laughter and companionship',
    botanicalDescription: 'Unforgettable adventures, heartfelt conversations, and quiet moments that deepened over time.',
    accentColor: '#F59E0B', // Warm amber
  },
  {
    id: 'celebration',
    name: 'Celebration in Bloom',
    tagline: 'Full petals radiating love and milestone joy',
    botanicalDescription: 'Grand milestone celebrations, warmest wishes, and the golden warmth of shared happiness.',
    accentColor: '#FF6B6B', // Signature coral
  },
];

// 12 realistic placeholder memories for Birthday
const BIRTHDAY_MEMORIES: GardenMemory[] = [
  {
    id: 'gm-1',
    title: 'The Beginning',
    contributorName: 'Mom & Dad',
    contributorRole: 'Parents',
    contributorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&q=80',
    type: 'photo',
    content: 'From the very first day you came into this world, you brought sunshine into our lives. Watching you grow has been the greatest joy a parent could ever dream of.',
    mediaUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=1000&q=80',
    date: 'June 14, 2001',
    likesCount: 28,
    flowerType: 'rose',
    flowerVarietyName: 'Gentle Dawn Rosebud',
    bloomState: 'bud',
    flowerSize: 'medium',
    isHighlight: false,
    petalColor: '#FDA4AF', // Soft rose pink
    centerColor: '#F43F5E',
    leafColor: '#15803D',
    stemHeight: 65,
    rotation: -4,
    zone: 'beginning',
    x: 28,
    y: 260,
  },
  {
    id: 'gm-2',
    title: 'A Beautiful Day',
    contributorName: 'Grandma Rose',
    contributorRole: 'Grandmother',
    contributorAvatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=120&q=80',
    type: 'audio',
    content: 'I still remember you running through my rose garden with your little watering can. You always cared for every blossom with so much gentleness and love.',
    mediaUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1000&q=80',
    audioUrl: 'https://cdn.freesound.org/previews/264/264498_4284968-lq.mp3',
    duration: '0:42',
    date: 'August 22, 2008',
    likesCount: 35,
    flowerType: 'peony',
    flowerVarietyName: 'Grandma’s Heirloom Peony',
    bloomState: 'blooming',
    flowerSize: 'large',
    isHighlight: true, // Special highlighted flower
    petalColor: '#F472B6', // Warm rose
    centerColor: '#BE185D',
    leafColor: '#166534',
    stemHeight: 80,
    rotation: 6,
    zone: 'beginning',
    x: 72,
    y: 420,
  },
  {
    id: 'gm-3',
    title: 'Our Favorite Moment',
    contributorName: 'Mia Chen',
    contributorRole: 'Best Friend',
    contributorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
    type: 'photo',
    content: 'That spontaneous road trip to the coast when our car had a flat tire, and we spent three hours eating strawberry ice cream watching the waves crash under the lighthouse.',
    mediaUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=80',
    date: 'July 19, 2019',
    likesCount: 42,
    flowerType: 'daisy',
    flowerVarietyName: 'Golden Summer Daisy',
    bloomState: 'full-bloom',
    flowerSize: 'medium',
    isHighlight: false,
    petalColor: '#FEF08A', // Buttercream yellow
    centerColor: '#D97706',
    leafColor: '#15803D',
    stemHeight: 60,
    rotation: -8,
    zone: 'beginning',
    x: 34,
    y: 600,
  },
  {
    id: 'gm-4',
    title: 'Little Things',
    contributorName: 'Ethan Vance',
    contributorRole: 'Brother',
    contributorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
    type: 'wish',
    content: 'It’s the quiet Sunday mornings playing old board games, arguing over trivial rules, and laughing until our stomachs hurt. You’ll always be my favorite teammate in life.',
    mediaUrl: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?auto=format&fit=crop&w=1000&q=80',
    date: 'May 3, 2021',
    likesCount: 19,
    flowerType: 'lavender',
    flowerVarietyName: 'Provence Wild Lavender',
    bloomState: 'blooming',
    flowerSize: 'small',
    isHighlight: false,
    petalColor: '#C084FC', // Soft lavender
    centerColor: '#7E22CE',
    leafColor: '#166534',
    stemHeight: 55,
    rotation: 5,
    zone: 'beginning',
    x: 68,
    y: 780,
  },
  {
    id: 'gm-5',
    title: 'Endless Laughter',
    contributorName: 'Sophia & the Girls',
    contributorRole: 'College Circle',
    contributorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80',
    type: 'video',
    content: 'We recorded this late-night dance party in our tiny dorm room. No choreography, just sheer joy and the best humans alive. May your year be as uninhibited and joyful!',
    mediaUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80',
    duration: '1:18',
    date: 'October 11, 2021',
    likesCount: 51,
    flowerType: 'hydrangea',
    flowerVarietyName: 'Sky Blue Hydrangea Cluster',
    bloomState: 'full-bloom',
    flowerSize: 'large',
    isHighlight: true, // Prominent highlight memory
    petalColor: '#93C5FD', // Soft sky blue
    centerColor: '#2563EB',
    leafColor: '#15803D',
    stemHeight: 85,
    rotation: -3,
    zone: 'moments',
    x: 24,
    y: 1040,
  },
  {
    id: 'gm-6',
    title: 'A Special Surprise',
    contributorName: 'Aunt Claire',
    contributorRole: 'Aunt',
    contributorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=120&q=80',
    type: 'photo',
    content: 'When we secretly flew into town to surprise you for dinner. That look of absolute shock and happiness on your face is etched in my memory forever.',
    mediaUrl: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1000&q=80',
    date: 'November 28, 2022',
    likesCount: 31,
    flowerType: 'camellia',
    flowerVarietyName: 'Winter Pearl Camellia',
    bloomState: 'blooming',
    flowerSize: 'medium',
    isHighlight: false,
    petalColor: '#FB7185', // Soft coral rose
    centerColor: '#BE123C',
    leafColor: '#166534',
    stemHeight: 65,
    rotation: 7,
    zone: 'moments',
    x: 76,
    y: 1220,
  },
  {
    id: 'gm-7',
    title: 'Together Again',
    contributorName: 'High School Crew',
    contributorRole: 'Lifelong Friends',
    contributorAvatar: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=120&q=80',
    type: 'photo',
    content: 'Five years after graduation, meeting back at our hometown diner like no time had passed. Some roots run so deep that seasons can never weaken them.',
    mediaUrl: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1000&q=80',
    date: 'December 26, 2022',
    likesCount: 38,
    flowerType: 'calla-lily',
    flowerVarietyName: 'Ivory Grace Calla Lily',
    bloomState: 'blooming',
    flowerSize: 'medium',
    isHighlight: false,
    petalColor: '#FEF9C3', // Warm cream
    centerColor: '#CA8A04',
    leafColor: '#15803D',
    stemHeight: 70,
    rotation: -5,
    zone: 'moments',
    x: 32,
    y: 1400,
  },
  {
    id: 'gm-8',
    title: 'One to Remember',
    contributorName: 'David Lee',
    contributorRole: 'Mentor',
    contributorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&q=80',
    type: 'audio',
    content: 'Sarah, watching your dedication and resilience when things felt uncertain proved to everyone the extraordinary heart you have. You inspire everyone who walks beside you.',
    mediaUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80',
    audioUrl: 'https://cdn.freesound.org/previews/320/320655_5260872-lq.mp3',
    duration: '0:56',
    date: 'March 14, 2023',
    likesCount: 44,
    flowerType: 'cherry-blossom',
    flowerVarietyName: 'Spring Cherry Blossom',
    bloomState: 'full-bloom',
    flowerSize: 'medium',
    isHighlight: false,
    petalColor: '#FBCFE8', // Sakura blossom pink
    centerColor: '#DB2777',
    leafColor: '#166534',
    stemHeight: 62,
    rotation: 4,
    zone: 'moments',
    x: 65,
    y: 1580,
  },
  {
    id: 'gm-9',
    title: 'The Celebration',
    contributorName: 'Maya & Liam',
    contributorRole: 'Cousins',
    contributorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=120&q=80',
    type: 'photo',
    content: 'Golden hour in the garden with fairy lights overhead and acoustic guitar playing softly. Everyone gathered around to toast to another incredible chapter of your life.',
    mediaUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80',
    date: 'June 10, 2023',
    likesCount: 67,
    flowerType: 'peony',
    flowerVarietyName: 'Imperial Coral Peony',
    bloomState: 'full-bloom',
    flowerSize: 'large',
    isHighlight: true, // Special highlight memory
    petalColor: '#FF6B6B', // Signature coral!
    centerColor: '#991B1B',
    leafColor: '#15803D',
    stemHeight: 88,
    rotation: -2,
    zone: 'celebration',
    x: 30,
    y: 1840,
  },
  {
    id: 'gm-10',
    title: 'A Memory to Keep',
    contributorName: 'Uncle Robert',
    contributorRole: 'Uncle',
    contributorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&q=80',
    type: 'wish',
    content: 'True wisdom is knowing that every day is a gift. You bring kindness into rooms before you even speak. Never lose that bright, generous spirit of yours.',
    mediaUrl: 'https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?auto=format&fit=crop&w=1000&q=80',
    date: 'January 15, 2024',
    likesCount: 26,
    flowerType: 'rose',
    flowerVarietyName: 'Velvet English Rose',
    bloomState: 'full-bloom',
    flowerSize: 'medium',
    isHighlight: false,
    petalColor: '#E11D48', // Deep velvet red
    centerColor: '#881337',
    leafColor: '#166534',
    stemHeight: 68,
    rotation: 6,
    zone: 'celebration',
    x: 74,
    y: 2020,
  },
  {
    id: 'gm-11',
    title: 'With Love',
    contributorName: 'Chloe Vance',
    contributorRole: 'Sister',
    contributorAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=120&q=80',
    type: 'photo',
    content: 'To my sister, confidante, and lifelong anchor: through every season of life, your love has been a constant shelter. Here’s to dreaming bigger, laughing louder, and blooming brighter.',
    mediaUrl: 'https://images.unsplash.com/photo-1531747056595-07f6cbbe10ad?auto=format&fit=crop&w=1000&q=80',
    date: 'May 20, 2024',
    likesCount: 58,
    flowerType: 'tulip',
    flowerVarietyName: 'Golden Sunburst Tulip',
    bloomState: 'blooming',
    flowerSize: 'medium',
    isHighlight: false,
    petalColor: '#F59E0B', // Warm amber gold
    centerColor: '#B45309',
    leafColor: '#15803D',
    stemHeight: 74,
    rotation: -6,
    zone: 'celebration',
    x: 35,
    y: 2200,
  },
  {
    id: 'gm-12',
    title: 'Until the Next Chapter',
    contributorName: 'All Your Loved Ones',
    contributorRole: 'Family & Friends',
    contributorAvatar: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=120&q=80',
    type: 'video',
    content: 'We compiled this group message with clips from everyone across four continents. Sarah, every single petal in this garden was planted with love. Happy Birthday!',
    mediaUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1000&q=80',
    duration: '2:45',
    date: 'June 14, 2024',
    likesCount: 94,
    flowerType: 'rose',
    flowerVarietyName: 'Centennial Grand Flora',
    bloomState: 'full-bloom',
    flowerSize: 'large',
    isHighlight: true, // Grand highlight finale
    petalColor: '#FF6B6B', // Platform Coral
    centerColor: '#BE123C',
    leafColor: '#14532D',
    stemHeight: 94,
    rotation: 0,
    zone: 'celebration',
    x: 52,
    y: 2420,
  },
];

// Presets for all occasion types
export const OCCASION_CONFIGS: Record<OccasionType, OccasionGardenConfig> = {
  Birthday: {
    occasionType: 'Birthday',
    personName: 'Sarah Vance',
    headerTitle: "Sarah's Birthday Garden",
    tagline: 'Every memory makes her story bloom.',
    accentColor: '#FF6B6B',
    centerpiece: {
      title: 'The Centennial Flowering Arbor',
      subtitle: 'Heart of the Memory Garden',
      emotionalQuote: '“Memories are the flowers of the heart, blooming through every season of our lives.”',
      memorialPlaque: 'Dedicated with infinite warmth on Sarah’s Birthday',
    },
    finalMessage: 'Every memory made this garden bloom.',
    finalQuote: 'From tiny seeds of shared laughter to full blossoms of lifelong friendship, every story here remains forever in bloom.',
    memories: BIRTHDAY_MEMORIES,
  },
  Anniversary: {
    occasionType: 'Anniversary',
    personName: 'Claire & Julian',
    headerTitle: 'Our Memory Garden',
    tagline: 'Every moment helped us grow together.',
    accentColor: '#E11D48',
    centerpiece: {
      title: 'The Everlasting Willow Bench',
      subtitle: 'Rooted in 25 Years of Devotion',
      emotionalQuote: '“True love is not just looking at each other, but walking side-by-side through our shared garden.”',
      memorialPlaque: 'Silver Anniversary Keepsake • Claire & Julian',
    },
    finalMessage: 'Every moment made our love bloom.',
    finalQuote: 'Two lives intertwined like flowering vines, flourishing stronger with each passing year.',
    memories: BIRTHDAY_MEMORIES.map((m, idx) => ({
      ...m,
      title: [
        'The First Date',
        'Our Little Apartment',
        'Summer in Tuscany',
        'Quiet Sunday Mornings',
        'The Day We Said I Do',
        'First House, First Garden',
        'Raising Our Family',
        'Midnight Conversations',
        'A Silver Milestone',
        'The Small Gestures',
        'Our Vows Renewed',
        'Forever Growing Together',
      ][idx],
      contributorName: [
        'Julian',
        'Claire',
        'Family Friends',
        'Julian',
        'The Wedding Party',
        'Claire',
        'Our Children',
        'Julian',
        'The Extended Family',
        'Claire',
        'Maid of Honor',
        'All Who Cherish You',
      ][idx],
    })),
  },
  Wedding: {
    occasionType: 'Wedding',
    personName: 'Emma & Lucas',
    headerTitle: 'Our Garden of Memories',
    tagline: 'Every beautiful moment brought us here.',
    accentColor: '#F59E0B',
    centerpiece: {
      title: 'The Botanical Wedding Pavilion',
      subtitle: 'Where Two Journeys Become One',
      emotionalQuote: '“Grow old along with me; the best is yet to be.”',
      memorialPlaque: 'In Celebration of Emma & Lucas • Forever in Bloom',
    },
    finalMessage: 'Every memory brought us to this day.',
    finalQuote: 'Surrounded by the blossoms of our family and dearest friends, our story is just beginning to flourish.',
    memories: BIRTHDAY_MEMORIES.map((m, idx) => ({
      ...m,
      title: [
        'How We Met',
        'The Sunset Proposal',
        'Bachelor & Bachelorette',
        'Parental Blessing',
        'Rehearsal Dinner Warmth',
        'Walking Down the Aisle',
        'The First Dance',
        'Grandparent Wisdom',
        'Toasts from Childhood Friends',
        'The Late-Night Sparklers',
        'A Promise Kept',
        'A Lifetime Together',
      ][idx],
    })),
  },
  Graduation: {
    occasionType: 'Graduation',
    personName: 'Marcus Wright',
    headerTitle: 'A Garden of Milestones',
    tagline: 'Every step became a memory.',
    accentColor: '#10B981',
    centerpiece: {
      title: 'The Scholar’s Ancient Oak',
      subtitle: 'Roots of Knowledge, Branches of Hope',
      emotionalQuote: '“Education is not the filling of a pail, but the lighting of a fire.”',
      memorialPlaque: 'Class of 2024 • Honors & Milestone Achievements',
    },
    finalMessage: 'Every milestone made your future bloom.',
    finalQuote: 'You have nurtured your dreams with hard work and integrity; now watch them branch out into the world.',
    memories: BIRTHDAY_MEMORIES.map((m, idx) => ({
      ...m,
      title: [
        'The First Acceptance Letter',
        'Late Night Study Sessions',
        'Dean’s List Recognition',
        'Roommate Shenanigans',
        'The Capstone Presentation',
        'Mentorship & Guidance',
        'Family Pride',
        'Internship Breakthrough',
        'Walking the Stage',
        'Tossing the Cap',
        'Wishes for the Horizon',
        'The Next Grand Chapter',
      ][idx],
    })),
  },
  'Bride to Be': {
    occasionType: 'Bride to Be',
    personName: 'Olivia Sterling',
    headerTitle: 'The Bridal Botanical Garden',
    tagline: 'Celebrating love in full bloom.',
    accentColor: '#EC4899',
    centerpiece: {
      title: 'The Rose Trellis Gazebo',
      subtitle: 'To the Bride-to-Be',
      emotionalQuote: '“A joyful heart makes the face blossom like a rose in spring.”',
      memorialPlaque: 'Bridal Keepsake Collection • Olivia’s Story',
    },
    finalMessage: 'Every memory surrounds you with love.',
    finalQuote: 'May your wedding day and marriage blossom with every ounce of joy you bring to everyone in this garden.',
    memories: BIRTHDAY_MEMORIES.map((m, idx) => ({
      ...m,
      title: [
        'Saying Yes to the Dress',
        'Bridal Shower Champagne',
        'Sister Secrets',
        'Childhood Memories',
        'The Maid of Honor Speech',
        'Something Borrowed, Something Blue',
        'Bachelorette Getaway',
        'Mother-Daughter Tears',
        'Counting Down the Days',
        'Advice for the Journey',
        'Radiant Bride-to-Be',
        'Cheers to the Mrs.',
      ][idx],
    })),
  },
  Other: {
    occasionType: 'Other',
    personName: 'Honored Guest',
    headerTitle: 'A Garden of Cherished Memories',
    tagline: 'Every memory makes our story bloom.',
    accentColor: '#FF6B6B',
    centerpiece: {
      title: 'The Community Sanctuary Tree',
      subtitle: 'Celebrating a Cherished Life',
      emotionalQuote: '“We do not remember days; we remember moments.”',
      memorialPlaque: 'Preserved in Timeless Bloom',
    },
    finalMessage: 'Every memory made this garden bloom.',
    finalQuote: 'Preserving the beauty of human connection across time and generations.',
    memories: BIRTHDAY_MEMORIES,
  },
};

export const getGardenConfig = (
  occasionType: OccasionType = 'Birthday',
  celebrationPersonName?: string
): OccasionGardenConfig => {
  const config = OCCASION_CONFIGS[occasionType] || OCCASION_CONFIGS.Birthday;
  if (!celebrationPersonName) return config;

  return {
    ...config,
    personName: celebrationPersonName,
    headerTitle:
      occasionType === 'Birthday'
        ? `${celebrationPersonName}’s Birthday Garden`
        : occasionType === 'Anniversary'
        ? `${celebrationPersonName}’s Memory Garden`
        : occasionType === 'Wedding'
        ? `${celebrationPersonName}’s Wedding Garden`
        : config.headerTitle,
  };
};
