import { OccasionType } from '../../../types';
import { OccasionConstellationConfig } from './types';

export const CONSTELLATION_CONFIGS: Record<OccasionType, OccasionConstellationConfig> = {
  Birthday: {
    occasionType: 'Birthday',
    personName: 'Sarah',
    headerTitle: "Sarah's 25th Birthday",
    tagline: 'Every memory is a star in her story.',
    centerpieceTitle: 'SARAH',
    centerpieceSubtitle: '13 Memories in Orbit',
    centerpieceQuote: '“To 25 radiant years of light, laughter, and lifelong friendship.”',
    accentColor: '#FF6B6B',
    ambientNebulae: [
      { x: 30, y: 25, color: 'rgba(255, 107, 107, 0.12)', radius: 360, opacity: 0.15 },
      { x: 70, y: 65, color: 'rgba(99, 102, 241, 0.14)', radius: 420, opacity: 0.2 },
      { x: 50, y: 45, color: 'rgba(251, 191, 36, 0.08)', radius: 300, opacity: 0.12 },
      { x: 20, y: 80, color: 'rgba(56, 189, 248, 0.1)', radius: 320, opacity: 0.14 },
    ],
    stars: [
      {
        id: 'star-b1',
        title: 'The Beginning: Freshman Year',
        subtitle: 'Dorm Room 304',
        contributorName: 'Emma Watson',
        contributorRole: 'College Roommate',
        contributorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
        type: 'photo',
        content:
          'Remember the very first night we unpacked our suitcases in room 304? We stayed up until 4 AM dividing playlists, eating stale pretzels, and dreaming about everything we were going to conquer.',
        mediaUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=80',
        date: 'Sept 14, 2018',
        likesCount: 18,
        x: 18,
        y: 28,
        size: 'medium',
        brightness: 'bright',
        starName: 'Alpha Prima',
        glowColor: '#FF6B6B',
        connections: ['star-b2', 'star-b5'],
        quote: 'We stayed up till 4 AM dividing playlists and dreaming big.',
      },
      {
        id: 'star-b2',
        title: 'Spontaneous Highway Roadtrip',
        subtitle: 'Pacific Coast Highway',
        contributorName: 'Marcus Chen',
        contributorRole: 'Adventurer & Friend',
        contributorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        type: 'photo',
        content:
          'We decided to rent the convertible with exactly one hour notice. Sarah had her hand out in the ocean wind singing Fleetwood Mac at the top of her lungs with zero regrets.',
        mediaUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1000&q=80',
        date: 'July 19, 2020',
        likesCount: 24,
        x: 32,
        y: 18,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Vespera Ventus',
        glowColor: '#38BDF8',
        connections: ['star-b3', 'star-b6'],
        quote: 'Hand out in the ocean wind, singing at the top of our lungs.',
      },
      {
        id: 'star-b3',
        title: 'The Rooftop Golden Hour',
        subtitle: 'Brooklyn Heights Sunset',
        contributorName: 'Chloe Bennett',
        contributorRole: 'Best Friend',
        contributorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
        type: 'photo',
        content:
          'One of those rare golden evenings where the city felt peaceful. You turned around just as the sun clipped behind the skyline. It remains my favorite photo of you in the entire decade.',
        mediaUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80',
        date: 'May 28, 2022',
        likesCount: 42,
        x: 48,
        y: 14,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Stella Aurora Major',
        glowColor: '#F59E0B',
        connections: ['star-b4', 'star-b7'],
        quote: 'The city felt quiet, the light was warm, and everything felt possible.',
      },
      {
        id: 'star-b4',
        title: 'Voice Note from Berlin',
        subtitle: 'Sent via WhatsApp',
        contributorName: 'Lucas Morales',
        contributorRole: 'Childhood Friend',
        contributorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        type: 'audio',
        duration: '0:48',
        content:
          '“Sarah! Sending the biggest bear hug from 4,000 miles away. You have always been the anchor in every room you walk into. Here’s a little voice memo so you know I’m raising a glass to you tonight!”',
        mediaUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
        date: '3 days ago',
        likesCount: 31,
        x: 68,
        y: 20,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Resonans Eos',
        glowColor: '#A78BFA',
        connections: ['star-b8'],
        quote: '“Sending the biggest bear hug from 4,000 miles away!”',
      },
      {
        id: 'star-b5',
        title: 'Midnight Baking Experiment',
        subtitle: 'Flour everywhere at 2 AM',
        contributorName: 'Elena Rostova',
        contributorRole: 'Sister',
        contributorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
        type: 'photo',
        content:
          'We set out to bake French macarons and ended up with sugary pancakes that tasted like heaven. Proof that even our kitchen disasters are filled with uncontrollable laughter.',
        mediaUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1000&q=80',
        date: 'Dec 12, 2021',
        likesCount: 19,
        x: 15,
        y: 45,
        size: 'small',
        brightness: 'soft',
        starName: 'Dulcis Lucis',
        glowColor: '#EC4899',
        connections: ['star-b9', 'star-b6'],
        quote: 'Proof that our kitchen disasters are the sweetest memories.',
      },
      {
        id: 'star-b6',
        title: 'Unstoppable Laughter Reel',
        subtitle: 'The Backyard Karaoke Session',
        contributorName: 'Sam & Maya',
        contributorRole: 'Cousins',
        contributorAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
        type: 'video',
        duration: '1:12',
        content:
          'Nothing encapsulates your vibrant soul better than this 70-second video of you laughing so hard you couldn’t hit the high note in ‘Dancing Queen’. Play it whenever you need an instant dose of joy!',
        mediaUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80',
        date: 'Aug 24, 2023',
        likesCount: 56,
        x: 34,
        y: 42,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Jovialis Corona',
        glowColor: '#FF6B6B',
        connections: ['star-b7', 'star-b10'],
        quote: 'Laughing so hard you could barely breathe—pure unfiltered joy.',
      },
      {
        id: 'star-b7',
        title: 'Letter from Mom & Dad',
        subtitle: 'Wishes for Quarter-Century',
        contributorName: 'Mom & Dad',
        contributorRole: 'Parents',
        contributorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        type: 'wish',
        content:
          'Dearest Sarah, Watching you grow into this fearless, kind, and brilliantly authentic woman has been the privilege of our lifetimes. May your 25th chapter be written with courage, soft mornings, deep friendships, and endless wonder.',
        date: '1 week ago',
        likesCount: 68,
        x: 62,
        y: 40,
        size: 'medium',
        brightness: 'bright',
        starName: 'Amoris Perpetua',
        glowColor: '#F59E0B',
        connections: ['star-b8', 'star-b11'],
        quote: '“Watching you grow has been the privilege of our lifetimes.”',
      },
      {
        id: 'star-b8',
        title: 'Campfire Under the Perseids',
        subtitle: 'Big Sur Stargazing Trip',
        contributorName: 'Julian Croft',
        contributorRole: 'Campfire Guitarist',
        contributorAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
        type: 'photo',
        content:
          'We counted 17 shooting stars that night bundled up in three woolen blankets. Sarah made a wish on the brightest one. It feels so fitting that today we celebrate her under her own constellation.',
        mediaUrl: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1000&q=80',
        date: 'Oct 08, 2022',
        likesCount: 29,
        x: 82,
        y: 35,
        size: 'medium',
        brightness: 'bright',
        starName: 'Perseus Igne',
        glowColor: '#38BDF8',
        connections: ['star-b12'],
        quote: 'We counted 17 shooting stars bundled in blankets by the fire.',
      },
      {
        id: 'star-b9',
        title: 'First Half Marathon Crossing',
        subtitle: 'Central Park Finish Line',
        contributorName: 'David K.',
        contributorRole: 'Running Buddy',
        contributorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=200&q=80',
        type: 'photo',
        content:
          'Mile 11 was brutal with the cold rain, but you grabbed my shoulder and said “we are crossing this together, no walking!” The grit and determination on your face is something I’ll always look up to.',
        mediaUrl: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?auto=format&fit=crop&w=1000&q=80',
        date: 'Nov 05, 2023',
        likesCount: 35,
        x: 20,
        y: 72,
        size: 'small',
        brightness: 'soft',
        starName: 'Fortis Vega',
        glowColor: '#10B981',
        connections: ['star-b10'],
        quote: 'Mile 11 was brutal, but you sprinted across with a massive grin.',
      },
      {
        id: 'star-b10',
        title: 'The Birthday Surprise Reveal',
        subtitle: 'The Moment She Walked In',
        contributorName: 'Everyone Together',
        contributorRole: 'Secret Co-conspirators',
        contributorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
        type: 'photo',
        content:
          'For six weeks we whispered behind your back to make tonight happen. When you opened the door and gasped, dropping your keys, that genuine shock and happy tear was worth every single secret group chat!',
        mediaUrl: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=1000&q=80',
        date: 'Tonight',
        likesCount: 89,
        x: 38,
        y: 68,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Mira Celestis',
        glowColor: '#FF6B6B',
        connections: ['star-b11', 'star-b13'],
        quote: 'Six weeks of secret planning for one unforgettable gasp of joy.',
      },
      {
        id: 'star-b11',
        title: 'Toast to the Next 25 Years',
        subtitle: 'Spoken Word Toast',
        contributorName: 'Auntie Grace',
        contributorRole: 'Godmother',
        contributorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
        type: 'audio',
        duration: '1:05',
        content:
          '“Sarah darling, your grandmother always said that some people are born with sunshine woven into their fibers. You have illuminated every room in our family since day one. May life return to you every bit of warmth you have poured out.”',
        mediaUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
        date: 'Yesterday',
        likesCount: 44,
        x: 60,
        y: 65,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Aura Serenitatis',
        glowColor: '#F59E0B',
        connections: ['star-b12'],
        quote: '“Some people are born with sunshine woven into their fibers.”',
      },
      {
        id: 'star-b12',
        title: 'Sunday Morning Coffee Ritual',
        subtitle: 'Our Corner Table at Cafe Fiore',
        contributorName: 'Maya Lin',
        contributorRole: 'Coffee Soulmate',
        contributorAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
        type: 'photo',
        content:
          'People talk about grand milestones, but my dearest memories with you are the quiet Sunday mornings dissecting books, sharing warm almond croissants, and plotting our futures over oat lattes.',
        mediaUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1000&q=80',
        date: 'Jan 14, 2024',
        likesCount: 27,
        x: 78,
        y: 62,
        size: 'small',
        brightness: 'soft',
        starName: 'Tranquilla Sol',
        glowColor: '#EC4899',
        connections: ['star-b13'],
        quote: 'Quiet Sunday mornings, warm croissants, and plotting our futures.',
      },
      {
        id: 'star-b13',
        title: 'A Wish for Endless Stars',
        subtitle: 'From All 18 Contributors',
        contributorName: 'The Whole Crew',
        contributorRole: 'Circle of Love',
        contributorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
        type: 'wish',
        content:
          'May every star in this constellation remind you that you are deeply loved, endlessly celebrated, and never walking this journey alone. Happy 25th birthday, Sarah!',
        date: 'Today',
        likesCount: 73,
        x: 52,
        y: 84,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Omega Aeterna',
        glowColor: '#38BDF8',
        connections: ['star-b9'],
        quote: '“May every star remind you that you are deeply, unconditionally loved.”',
      },
    ],
  },

  Anniversary: {
    occasionType: 'Anniversary',
    personName: 'Elena & Marcus',
    headerTitle: 'Our Constellation: 10 Years in Orbit',
    tagline: 'Every moment brought us here.',
    centerpieceTitle: 'OUR STORY',
    centerpieceSubtitle: '10 Years of Love',
    centerpieceQuote: '“A decade of ordinary days turned extraordinary together.”',
    accentColor: '#38BDF8',
    ambientNebulae: [
      { x: 25, y: 30, color: 'rgba(56, 189, 248, 0.15)', radius: 380, opacity: 0.18 },
      { x: 75, y: 55, color: 'rgba(236, 72, 153, 0.14)', radius: 410, opacity: 0.2 },
      { x: 50, y: 50, color: 'rgba(255, 107, 107, 0.08)', radius: 320, opacity: 0.12 },
    ],
    stars: [
      {
        id: 'star-a1',
        title: 'The Rainy Day Umbrella',
        subtitle: 'Union Square, 2014',
        contributorName: 'Elena',
        contributorRole: 'Wife',
        type: 'photo',
        content: 'You offered half your broken black umbrella when the skies opened over Union Square. Little did I know I had just met my forever person.',
        mediaUrl: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=1000&q=80',
        date: 'Oct 14, 2014',
        likesCount: 38,
        x: 20,
        y: 22,
        size: 'medium',
        brightness: 'bright',
        starName: 'Pluvia Amoris',
        glowColor: '#38BDF8',
        connections: ['star-a2', 'star-a4'],
        quote: 'You offered half your umbrella, and the rest is our history.',
      },
      {
        id: 'star-a2',
        title: 'The Paris Proposal',
        subtitle: 'Pont de Bir-Hakeim',
        contributorName: 'Marcus',
        contributorRole: 'Husband',
        type: 'photo',
        content: 'My hands were trembling so much I almost dropped the ring into the Seine. When you whispered yes through your tears, the whole world vanished.',
        mediaUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=80',
        date: 'June 21, 2017',
        likesCount: 92,
        x: 45,
        y: 16,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Stella Sequana',
        glowColor: '#FF6B6B',
        connections: ['star-a3', 'star-a6'],
        quote: 'My hands were trembling, but your yes gave me lifelong peace.',
      },
      {
        id: 'star-a3',
        title: 'Our Wedding Vows',
        subtitle: 'Big Sur Coastline',
        contributorName: 'Father Thomas',
        contributorRole: 'Officiant',
        type: 'audio',
        duration: '1:18',
        content: 'Listen to the exact moment Marcus promised to always make morning coffee, and Elena promised to always forgive his terrible puns.',
        mediaUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
        date: 'Sept 18, 2018',
        likesCount: 64,
        x: 76,
        y: 24,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Votum Aeternum',
        glowColor: '#F59E0B',
        connections: ['star-a7'],
        quote: '“To love in ordinary mornings and wild storms alike.”',
      },
      {
        id: 'star-a4',
        title: 'First Home Paint Fight',
        subtitle: 'Our Fixer-Upper Living Room',
        contributorName: 'Chloe',
        contributorRole: 'Sister',
        type: 'photo',
        content: 'Supposed to be painting the hallway dove gray. Turned into a full-scale roller war with sage green on your cheeks.',
        mediaUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
        date: 'April 03, 2019',
        likesCount: 27,
        x: 18,
        y: 52,
        size: 'small',
        brightness: 'soft',
        starName: 'Domus Primus',
        glowColor: '#10B981',
        connections: ['star-a5', 'star-a8'],
        quote: 'Turning a dusty hallway into a home filled with laughter.',
      },
      {
        id: 'star-a5',
        title: 'Welcoming Leo Home',
        subtitle: 'The Little Starlight',
        contributorName: 'Grandma Rose',
        contributorRole: 'Grandmother',
        type: 'photo',
        content: 'Holding your baby boy for the first time by the nursery window. Seeing you two step into parenthood together was pure poetry.',
        mediaUrl: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?auto=format&fit=crop&w=1000&q=80',
        date: 'Feb 11, 2021',
        likesCount: 88,
        x: 35,
        y: 45,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Nova Infans',
        glowColor: '#EC4899',
        connections: ['star-a6', 'star-a9'],
        quote: 'The day two became three, and our hearts multiplied by ten.',
      },
      {
        id: 'star-a6',
        title: 'Dancing in the Kitchen at 1 AM',
        subtitle: 'Recorded on phone camera',
        contributorName: 'Marcus',
        contributorRole: 'Husband',
        type: 'video',
        duration: '0:45',
        content: 'No music playing, just the hum of the refrigerator, barefoot, slow dancing like we were back in 2014.',
        mediaUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80',
        date: 'Nov 19, 2023',
        likesCount: 45,
        x: 62,
        y: 42,
        size: 'medium',
        brightness: 'bright',
        starName: 'Saltatio Media',
        glowColor: '#FF6B6B',
        connections: ['star-a7', 'star-a10'],
        quote: 'No music needed when you have each other to hold.',
      },
      {
        id: 'star-a7',
        title: 'Anniversary Trip to Amalfi',
        subtitle: 'Cliffside Lemon Groves',
        contributorName: 'Elena',
        contributorRole: 'Wife',
        type: 'photo',
        content: 'Overlooking Positano sipping limoncello. We promised that every ten years we would return to the sea to renew our gratitude.',
        mediaUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=80',
        date: 'Aug 04, 2024',
        likesCount: 52,
        x: 82,
        y: 50,
        size: 'medium',
        brightness: 'bright',
        starName: 'Amalphia Sol',
        glowColor: '#F59E0B',
        connections: ['star-a11'],
        quote: 'To the sea, to gratitude, and to our next decade.',
      },
      {
        id: 'star-a8',
        title: 'A Wish from Both Families',
        subtitle: 'United in Love',
        contributorName: 'The Family Council',
        contributorRole: 'Parents & Siblings',
        type: 'wish',
        content: 'You two have modeled what genuine partnership looks like: patient, playful, forgiving, and fiercely loyal. Happy 10th anniversary!',
        date: 'Today',
        likesCount: 61,
        x: 22,
        y: 78,
        size: 'medium',
        brightness: 'bright',
        starName: 'Familia Lumen',
        glowColor: '#38BDF8',
        connections: ['star-a9'],
        quote: '“Patient, playful, forgiving, and fiercely loyal.”',
      },
      {
        id: 'star-a9',
        title: 'Late Night Coffee Talks',
        subtitle: 'Balcony Conversations',
        contributorName: 'Elena',
        contributorRole: 'Wife',
        type: 'wish',
        content: 'Thank you for never letting an argument survive past midnight, and for being the safest place I have ever known in this universe.',
        date: '2 days ago',
        likesCount: 39,
        x: 42,
        y: 74,
        size: 'small',
        brightness: 'soft',
        starName: 'Refugium Noctis',
        glowColor: '#A78BFA',
        connections: ['star-a10'],
        quote: '“The safest place I have ever known in this universe.”',
      },
      {
        id: 'star-a10',
        title: 'The 10-Year Video Scrapbook',
        subtitle: 'Compilation from friends',
        contributorName: 'Best Friends Collective',
        contributorRole: 'Friend Circle',
        type: 'video',
        duration: '2:15',
        content: 'A 2-minute montage of your sweetest moments, roadtrips, funny bloopers, and quiet hugs collected secretly from everyone who loves you.',
        mediaUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=80',
        date: 'This week',
        likesCount: 77,
        x: 65,
        y: 70,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Chronos Decade',
        glowColor: '#FF6B6B',
        connections: ['star-a11', 'star-a12'],
        quote: 'Ten years of shared joy preserved in one radiant reel.',
      },
      {
        id: 'star-a11',
        title: 'Toast Across Time',
        subtitle: 'Grandma’s Special Blessing',
        contributorName: 'Grandma Elena',
        contributorRole: 'Matriarch',
        type: 'audio',
        duration: '0:55',
        content: '“May your love grow deeper than the roots of the olive trees and broader than the evening sky.”',
        mediaUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
        date: 'Yesterday',
        likesCount: 49,
        x: 80,
        y: 78,
        size: 'small',
        brightness: 'soft',
        starName: 'Benedictio',
        glowColor: '#F59E0B',
        connections: ['star-a12'],
        quote: '“May your love grow deeper than olive roots and broader than the sky.”',
      },
      {
        id: 'star-a12',
        title: 'To the Next Century Together',
        subtitle: 'Our Eternal Vow',
        contributorName: 'Marcus & Elena',
        contributorRole: 'Together',
        type: 'wish',
        content: 'Here is to the next decade, the next hundred journeys, and all the quiet moments in between. You will always be my northern star.',
        date: 'Today',
        likesCount: 95,
        x: 50,
        y: 86,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Polaris Amor',
        glowColor: '#38BDF8',
        connections: ['star-a8'],
        quote: '“You will always be my northern star.”',
      },
    ],
  },

  Wedding: {
    occasionType: 'Wedding',
    personName: 'Clara & James',
    headerTitle: 'Our Story in Stars',
    tagline: 'Every beautiful moment brought us here.',
    centerpieceTitle: 'CLARA & JAMES',
    centerpieceSubtitle: 'United in Starlight',
    centerpieceQuote: '“Two orbits aligning into one harmonious forever.”',
    accentColor: '#F59E0B',
    ambientNebulae: [
      { x: 30, y: 25, color: 'rgba(245, 158, 11, 0.12)', radius: 360, opacity: 0.16 },
      { x: 70, y: 65, color: 'rgba(255, 107, 107, 0.12)', radius: 400, opacity: 0.18 },
      { x: 50, y: 45, color: 'rgba(167, 139, 250, 0.1)', radius: 320, opacity: 0.15 },
    ],
    stars: [
      {
        id: 'star-w1',
        title: 'First Date Coffee Spill',
        subtitle: 'SoHo Rainy Morning',
        contributorName: 'James',
        contributorRole: 'Groom',
        type: 'photo',
        content: 'I was so nervous I knocked over my cappuccino. Clara just burst out laughing and handed me her napkin. That was the minute I fell.',
        mediaUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=80',
        date: 'March 14, 2019',
        likesCount: 44,
        x: 20,
        y: 25,
        size: 'medium',
        brightness: 'bright',
        starName: 'Primus Nexus',
        glowColor: '#F59E0B',
        connections: ['star-w2', 'star-w4'],
        quote: 'Nervous spilled coffee turned into lifelong devotion.',
      },
      {
        id: 'star-w2',
        title: 'Sunset Proposal at Big Sur',
        subtitle: 'The Ocean Cliffs',
        contributorName: 'Clara',
        contributorRole: 'Bride',
        type: 'photo',
        content: 'When he went down on one knee as the purple dusk blanketed the Pacific, I felt like the whole universe held its breath.',
        mediaUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=80',
        date: 'Sept 04, 2022',
        likesCount: 98,
        x: 48,
        y: 18,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Occasus Aeternus',
        glowColor: '#FF6B6B',
        connections: ['star-w3', 'star-w6'],
        quote: 'The purple dusk over the Pacific and the sweetest question ever asked.',
      },
      {
        id: 'star-w3',
        title: 'Rehearsal Dinner Toast',
        subtitle: 'Best Man Speech',
        contributorName: 'Marcus',
        contributorRole: 'Best Man',
        type: 'audio',
        duration: '1:10',
        content: '“James has spent his entire life looking for an adventure partner who could match his stubborn optimism. Clara, you are his dream come true.”',
        mediaUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
        date: 'Last Night',
        likesCount: 52,
        x: 75,
        y: 22,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Fidelis Frater',
        glowColor: '#38BDF8',
        connections: ['star-w7'],
        quote: '“Clara, you are the adventure partner he always dreamed of.”',
      },
      {
        id: 'star-w4',
        title: 'Mother of the Bride Blessing',
        subtitle: 'Handwritten Vows Note',
        contributorName: 'Eleanor Vance',
        contributorRole: 'Mother of the Bride',
        type: 'wish',
        content: 'To my precious daughter: Love is not a single day of celebration, but a thousand quiet decisions to hold hands through the dark. May God bless your marriage abundantly.',
        date: 'Today',
        likesCount: 86,
        x: 18,
        y: 50,
        size: 'medium',
        brightness: 'bright',
        starName: 'Materna Lux',
        glowColor: '#EC4899',
        connections: ['star-w5', 'star-w8'],
        quote: '“Love is a thousand quiet decisions to hold hands through the dark.”',
      },
      {
        id: 'star-w5',
        title: 'The First Dance',
        subtitle: 'Under Fairy Lights',
        contributorName: 'The Wedding Party',
        contributorRole: 'Friends & Family',
        type: 'video',
        duration: '1:45',
        content: 'Swirling under the canopy of glowing fairy lights to Etta James. Not a dry eye left in the entire garden hall.',
        mediaUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80',
        date: 'Tonight',
        likesCount: 110,
        x: 36,
        y: 44,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Prima Saltatio',
        glowColor: '#F59E0B',
        connections: ['star-w6', 'star-w9'],
        quote: 'Swirling under fairy lights with pure tears of happiness.',
      },
      {
        id: 'star-w6',
        title: 'The Wedding Cake Cutting',
        subtitle: 'Sparklers and Cheers',
        contributorName: 'Chef Antoine',
        contributorRole: 'Pastry Master',
        type: 'photo',
        content: 'Three-tier vanilla bean cake decorated with edible stardust sugar pearls. Clara got icing on James’s nose, exactly as planned!',
        mediaUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=1000&q=80',
        date: 'Tonight',
        likesCount: 65,
        x: 62,
        y: 42,
        size: 'medium',
        brightness: 'bright',
        starName: 'Dulcedo Coniugii',
        glowColor: '#FF6B6B',
        connections: ['star-w7', 'star-w10'],
        quote: 'Edible stardust and icing on the groom’s nose!',
      },
      {
        id: 'star-w7',
        title: 'Honeymoon Sendoff Whispers',
        subtitle: 'Airport Goodbyes',
        contributorName: 'Maid of Honor Sophie',
        contributorRole: 'Maid of Honor',
        type: 'audio',
        duration: '0:42',
        content: '“Bon voyage you two! Don’t check your emails, drink all the Italian espresso, and soak in every second of being newlyweds!”',
        mediaUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
        date: 'Just now',
        likesCount: 38,
        x: 82,
        y: 48,
        size: 'small',
        brightness: 'soft',
        starName: 'Iter Amoris',
        glowColor: '#38BDF8',
        connections: ['star-w11'],
        quote: '“Drink all the Italian espresso and soak in being newlyweds!”',
      },
      {
        id: 'star-w8',
        title: 'Our Vow Booklets',
        subtitle: 'Hand-lettered Gold Foil',
        contributorName: 'Clara & James',
        contributorRole: 'The Couple',
        type: 'wish',
        content: 'Written in secret over six months. “I promise to choose you when it is easy, and fight for you when it is hard. You are my home.”',
        date: 'Today',
        likesCount: 78,
        x: 20,
        y: 75,
        size: 'medium',
        brightness: 'bright',
        starName: 'Vota Sacra',
        glowColor: '#F59E0B',
        connections: ['star-w9'],
        quote: '“I promise to choose you when easy, and fight for you when hard.”',
      },
      {
        id: 'star-w9',
        title: 'The Sparkler Tunnel Exit',
        subtitle: 'Midnight sendoff',
        contributorName: 'All Wedding Guests',
        contributorRole: 'Celebrants',
        type: 'photo',
        content: 'Running through fifty crackling golden sparklers into the vintage getaway car. The most magical conclusion to day one of forever.',
        mediaUrl: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1000&q=80',
        date: 'Midnight',
        likesCount: 95,
        x: 40,
        y: 72,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Ignis Gaudii',
        glowColor: '#FF6B6B',
        connections: ['star-w10', 'star-w12'],
        quote: 'Running through golden sparklers into the beginning of forever.',
      },
      {
        id: 'star-w10',
        title: 'Toast from Grandpa George',
        subtitle: '60 Years Married Wisdom',
        contributorName: 'Grandpa George',
        contributorRole: 'Grandfather',
        type: 'wish',
        content: '“Never go to sleep angry. Say thank you for the smallest cups of tea. And remember that true love is an act of daily giving.”',
        date: 'Today',
        likesCount: 84,
        x: 64,
        y: 68,
        size: 'small',
        brightness: 'soft',
        starName: 'Sapientia Senex',
        glowColor: '#A78BFA',
        connections: ['star-w11', 'star-w13'],
        quote: '“True love is an act of daily, unconditional giving.”',
      },
      {
        id: 'star-w11',
        title: 'Sunset Boat in Lake Como',
        subtitle: 'Looking Forward',
        contributorName: 'James',
        contributorRole: 'Groom',
        type: 'photo',
        content: 'Our dreams of the future: the family we will raise, the porch we will build, the years we will spend laughing just like tonight.',
        mediaUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
        date: 'Looking Ahead',
        likesCount: 46,
        x: 82,
        y: 75,
        size: 'small',
        brightness: 'soft',
        starName: 'Lacus Serenus',
        glowColor: '#38BDF8',
        connections: ['star-w13'],
        quote: 'Dreaming of porch sunsets and decades of quiet laughter.',
      },
      {
        id: 'star-w12',
        title: 'Family Group Starlight Blessing',
        subtitle: 'Signed by 45 Relatives',
        contributorName: 'The Combined Families',
        contributorRole: 'Family',
        type: 'wish',
        content: 'Two wonderful families woven into one tonight. May your household always be filled with open doors, warm bread, and eternal love.',
        date: 'Today',
        likesCount: 71,
        x: 48,
        y: 86,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Concordia Familiae',
        glowColor: '#10B981',
        connections: ['star-w8'],
        quote: '“May your household always be filled with open doors and eternal love.”',
      },
      {
        id: 'star-w13',
        title: 'The Eternal Constellation',
        subtitle: 'Our Sky Forever',
        contributorName: 'Clara & James',
        contributorRole: 'Newlyweds',
        type: 'wish',
        content: 'Thank you to everyone who made this celestial evening unforgettable. This starry sky will live in our hearts forever.',
        date: 'Tonight',
        likesCount: 104,
        x: 68,
        y: 84,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Stella Coniugalis',
        glowColor: '#F59E0B',
        connections: ['star-w12'],
        quote: '“This starry sky of memories will live in our hearts forever.”',
      },
    ],
  },

  'Bride to Be': {
    occasionType: 'Bride to Be',
    personName: 'Clara',
    headerTitle: "Clara's Bridal Constellation",
    tagline: 'Surrounded by love, sisterhood, and starlight.',
    centerpieceTitle: 'BRIDE TO BE',
    centerpieceSubtitle: 'Clara’s Orbit of Love',
    centerpieceQuote: '“To the bride who brightens every room she steps into.”',
    accentColor: '#EC4899',
    ambientNebulae: [
      { x: 30, y: 30, color: 'rgba(236, 72, 153, 0.14)', radius: 360, opacity: 0.18 },
      { x: 70, y: 60, color: 'rgba(255, 107, 107, 0.12)', radius: 400, opacity: 0.18 },
      { x: 50, y: 45, color: 'rgba(245, 158, 11, 0.08)', radius: 300, opacity: 0.12 },
    ],
    stars: [
      {
        id: 'star-bb1',
        title: 'The Bridal Shower Toast',
        subtitle: 'Garden Mimosa Brunch',
        contributorName: 'Maid of Honor Sophie',
        contributorRole: 'Sister & MOH',
        type: 'photo',
        content: 'Watching you open your bridal gifts surrounded by three generations of women who adore you. You look ethereal in that white linen dress!',
        mediaUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80',
        date: 'Last Weekend',
        likesCount: 38,
        x: 22,
        y: 26,
        size: 'medium',
        brightness: 'bright',
        starName: 'Sponsa Alba',
        glowColor: '#EC4899',
        connections: ['star-bb2', 'star-bb4'],
        quote: 'Surrounded by three generations of women who adore you.',
      },
      {
        id: 'star-bb2',
        title: 'Saying Yes to the Dress',
        subtitle: 'The Atelier Tearjerker',
        contributorName: 'Mom & Clara',
        contributorRole: 'Family',
        type: 'photo',
        content: 'When the stylist zipped the pearls down the back and you turned to the mirror, mom’s jaw dropped and we all reached for tissues. You are stunning.',
        mediaUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1000&q=80',
        date: '2 months ago',
        likesCount: 76,
        x: 48,
        y: 18,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Vesta Margaritata',
        glowColor: '#F59E0B',
        connections: ['star-bb3', 'star-bb6'],
        quote: 'Zipped the pearls, turned to the mirror, and the room fell silent.',
      },
      {
        id: 'star-bb3',
        title: 'Advice from the Matron of Honor',
        subtitle: 'Voice Note of Love',
        contributorName: 'Aunt Diane',
        contributorRole: 'Aunt',
        type: 'audio',
        duration: '0:50',
        content: '“Clara sweetie, being a bride is a day, but being a wife is an art form. Keep laughing at his jokes and never let the romance go cold!”',
        mediaUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
        date: '3 days ago',
        likesCount: 29,
        x: 75,
        y: 24,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Vox Sororis',
        glowColor: '#38BDF8',
        connections: ['star-bb7'],
        quote: '“Being a bride is a day, but being a wife is an art form.”',
      },
      {
        id: 'star-bb4',
        title: 'Bachelorette Weekend in Tulum',
        subtitle: 'Sunset Cenote Jump',
        contributorName: 'Bridesmaids Squad',
        contributorRole: 'Best Friends',
        type: 'video',
        duration: '1:02',
        content: 'Ten girls holding hands jumping into the turquoise cenote at dusk shouting Clara’s name! The most unforgettable girls trip ever.',
        mediaUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80',
        date: '3 weeks ago',
        likesCount: 82,
        x: 18,
        y: 54,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Cenote Aqua',
        glowColor: '#FF6B6B',
        connections: ['star-bb5', 'star-bb8'],
        quote: 'Ten best friends jumping into turquoise waters shouting your name!',
      },
      {
        id: 'star-bb5',
        title: 'Childhood Dress-Up Memory',
        subtitle: 'Pillowcase Veils in 2004',
        contributorName: 'Sophie',
        contributorRole: 'Sister',
        type: 'photo',
        content: 'Remember pinning mom’s lace curtains to your hair with bobby pins and practicing your walk down the upstairs hallway? Now you are doing it for real!',
        mediaUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=80',
        date: 'Summer 2004',
        likesCount: 47,
        x: 35,
        y: 46,
        size: 'small',
        brightness: 'soft',
        starName: 'Infans Somnium',
        glowColor: '#EC4899',
        connections: ['star-bb6', 'star-bb9'],
        quote: 'Pillowcase veils in the hallway, now walking down the aisle for real.',
      },
      {
        id: 'star-bb6',
        title: 'Groom’s Secret Love Letter',
        subtitle: 'Read with coffee this morning',
        contributorName: 'James',
        contributorRole: 'Fiancé',
        type: 'wish',
        content: 'I count down the hours until I get to call you my wife. You are the kindest, smartest, most radiant human I have ever known. See you at the altar.',
        date: 'This Morning',
        likesCount: 94,
        x: 64,
        y: 44,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Epistula Sponsi',
        glowColor: '#F59E0B',
        connections: ['star-bb7', 'star-bb10'],
        quote: '“I count down the hours until I get to call you my wife.”',
      },
      {
        id: 'star-bb7',
        title: 'Pajama Party Secrets',
        subtitle: 'Midnight Face Masks',
        contributorName: 'College Besties',
        contributorRole: 'Bridal Party',
        type: 'photo',
        content: 'Late night giggles, green clay masks, and reviewing the seating chart for the tenth time. We love you so much Clara!',
        mediaUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=80',
        date: 'Last Night',
        likesCount: 35,
        x: 82,
        y: 52,
        size: 'small',
        brightness: 'soft',
        starName: 'Gaudium Noctis',
        glowColor: '#38BDF8',
        connections: ['star-bb11'],
        quote: 'Late night giggles, green face masks, and boundless sisterhood.',
      },
      {
        id: 'star-bb8',
        title: 'Something Old, Something New',
        subtitle: 'Grandmother’s Sapphire Ring',
        contributorName: 'Grandma Eleanor',
        contributorRole: 'Grandmother',
        type: 'photo',
        content: 'Tucking grandmother’s heirloom blue sapphire brooch into your bridal bouquet wrap so you carry our blessings with every step.',
        mediaUrl: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=1000&q=80',
        date: 'Yesterday',
        likesCount: 58,
        x: 22,
        y: 78,
        size: 'medium',
        brightness: 'bright',
        starName: 'Sapphirus Avia',
        glowColor: '#38BDF8',
        connections: ['star-bb9'],
        quote: 'Carrying three generations of love in your bridal bouquet wrap.',
      },
      {
        id: 'star-bb9',
        title: 'Bridesmaid Vow of Support',
        subtitle: 'Our Pact of Friendship',
        contributorName: 'All 6 Bridesmaids',
        contributorRole: 'Guardians of the Bride',
        type: 'wish',
        content: 'We promise to fix your veil, hold your bouquet, sneak you champagne, dance till our feet hurt, and always be your cheerleaders.',
        date: 'Today',
        likesCount: 66,
        x: 42,
        y: 72,
        size: 'small',
        brightness: 'soft',
        starName: 'Foedus Sororum',
        glowColor: '#EC4899',
        connections: ['star-bb10'],
        quote: '“We promise to dance till our feet hurt and always cheer for you.”',
      },
      {
        id: 'star-bb10',
        title: 'Morning Song for the Bride',
        subtitle: 'Acoustic Guitar Serenade',
        contributorName: 'Brother Liam',
        contributorRole: 'Brother',
        type: 'audio',
        duration: '1:15',
        content: 'An acoustic guitar recording written especially for Clara on her wedding morning. Soft, sweet, and full of heartfelt pride.',
        mediaUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
        date: 'This Morning',
        likesCount: 62,
        x: 64,
        y: 70,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Canticum Matutinum',
        glowColor: '#F59E0B',
        connections: ['star-bb11', 'star-bb12'],
        quote: 'An acoustic guitar song written for Clara on her wedding morning.',
      },
      {
        id: 'star-bb11',
        title: 'The Final Single Toast',
        subtitle: 'Champagne Flutes Clinking',
        contributorName: 'Bridal Suite',
        contributorRole: 'Squad',
        type: 'photo',
        content: 'Six champagne flutes touching with strawberry slices. The very last toast before you walk down the aisle as Clara Jenkins!',
        mediaUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80',
        date: '1 hour ago',
        likesCount: 49,
        x: 80,
        y: 78,
        size: 'small',
        brightness: 'soft',
        starName: 'Spumans Gaudium',
        glowColor: '#FF6B6B',
        connections: ['star-bb12'],
        quote: 'The final toast before stepping forward into forever.',
      },
      {
        id: 'star-bb12',
        title: 'A Story Written in the Stars',
        subtitle: 'Forever Loved',
        contributorName: 'Everyone Who Loves You',
        contributorRole: 'Bridal Circle',
        type: 'wish',
        content: 'Walk with your head high and your heart full Clara. You are cherished beyond measure. Go marry your best friend!',
        date: 'Now',
        likesCount: 88,
        x: 52,
        y: 86,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Stella Clara',
        glowColor: '#EC4899',
        connections: ['star-bb8'],
        quote: '“Walk with your head high and your heart full. Go marry your best friend!”',
      },
    ],
  },

  Graduation: {
    occasionType: 'Graduation',
    personName: 'Alexander',
    headerTitle: 'The Journey So Far: Class of 2024',
    tagline: 'Every milestone became a star in the sky.',
    centerpieceTitle: 'ALEXANDER',
    centerpieceSubtitle: 'Class of 2024 • Honors',
    centerpieceQuote: '“To bold minds, late nights in the lab, and boundless horizons.”',
    accentColor: '#10B981',
    ambientNebulae: [
      { x: 30, y: 30, color: 'rgba(16, 185, 129, 0.14)', radius: 360, opacity: 0.18 },
      { x: 70, y: 60, color: 'rgba(56, 189, 248, 0.14)', radius: 400, opacity: 0.18 },
      { x: 50, y: 45, color: 'rgba(245, 158, 11, 0.08)', radius: 300, opacity: 0.12 },
    ],
    stars: [
      {
        id: 'star-g1',
        title: 'Move-in Day & Empty Boxes',
        subtitle: 'Freshman Dorms, 2020',
        contributorName: 'Dad',
        contributorRole: 'Father',
        type: 'photo',
        content: 'Dropping you off during the pandemic with two suitcases and a desk fan. You were nervous, but that hunger to learn was in your eyes.',
        mediaUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1000&q=80',
        date: 'Sept 2020',
        likesCount: 34,
        x: 20,
        y: 24,
        size: 'medium',
        brightness: 'bright',
        starName: 'Initium Gradus',
        glowColor: '#10B981',
        connections: ['star-g2', 'star-g4'],
        quote: 'Two suitcases, a desk fan, and an unshakeable hunger to learn.',
      },
      {
        id: 'star-g2',
        title: 'The Capstone Project Breakthrough',
        subtitle: 'Robotics Lab 3 AM',
        contributorName: 'Prof. Henderson',
        contributorRole: 'Faculty Mentor',
        type: 'photo',
        content: 'When the autonomous rover algorithm finally converged after 14 sleepless failed runs. Alex jumped on the swivel chair and spun in circles!',
        mediaUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1000&q=80',
        date: 'March 2024',
        likesCount: 68,
        x: 48,
        y: 18,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Ingenium Victor',
        glowColor: '#38BDF8',
        connections: ['star-g3', 'star-g6'],
        quote: 'The algorithm converged at 3 AM and the whole lab erupted in cheers.',
      },
      {
        id: 'star-g3',
        title: 'Study Hall Roast & Laughs',
        subtitle: 'Library Basement Audio',
        contributorName: 'Study Group Crew',
        contributorRole: 'Engineering Buddies',
        type: 'audio',
        duration: '0:45',
        content: 'Hilarious audio snippet of Alex trying to explain quantum entanglement using slices of cafeteria pizza at 2 AM before finals.',
        mediaUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
        date: 'Dec 2023',
        likesCount: 41,
        x: 75,
        y: 22,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Philosophia Pizza',
        glowColor: '#F59E0B',
        connections: ['star-g7'],
        quote: 'Explaining quantum physics using slices of pepperoni pizza.',
      },
      {
        id: 'star-g4',
        title: 'First Internship Acceptance',
        subtitle: 'Silicon Valley Offer Letter',
        contributorName: 'Alex',
        contributorRole: 'Graduate',
        type: 'photo',
        content: 'The email arrived while standing in line at the coffee cart. Proof that all the late night coding marathons were leading somewhere incredible.',
        mediaUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1000&q=80',
        date: 'May 2023',
        likesCount: 52,
        x: 18,
        y: 52,
        size: 'small',
        brightness: 'soft',
        starName: 'Epistula Triumph',
        glowColor: '#10B981',
        connections: ['star-g5', 'star-g8'],
        quote: 'Proof that the late-night coding grinds were carving a future.',
      },
      {
        id: 'star-g5',
        title: 'Dean’s Honor Roll Ceremony',
        subtitle: 'Summa Cum Laude Recognition',
        contributorName: 'Mom',
        contributorRole: 'Proud Mother',
        type: 'photo',
        content: 'Pinned the honor medallion around your neck with tears in my eyes. You earned every single grain of this accomplishment with integrity.',
        mediaUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
        date: 'April 2024',
        likesCount: 84,
        x: 35,
        y: 44,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Corona Laudis',
        glowColor: '#F59E0B',
        connections: ['star-g6', 'star-g9'],
        quote: '“You earned every grain of this accomplishment with sheer integrity.”',
      },
      {
        id: 'star-g6',
        title: 'The Mortarboard Cap Toss',
        subtitle: 'Commencement Stadium',
        contributorName: 'Class of 2024',
        contributorRole: 'Graduates',
        type: 'video',
        duration: '0:58',
        content: 'Thousands of blue caps flying into the clear blue summer sky as the bells rang out across campus. We finally did it!',
        mediaUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
        date: 'Yesterday',
        likesCount: 96,
        x: 64,
        y: 42,
        size: 'large',
        brightness: 'radiant',
        isSpecial: true,
        starName: 'Volatus Galeri',
        glowColor: '#38BDF8',
        connections: ['star-g7', 'star-g10'],
        quote: 'Caps sailing into the azure sky—the sweetest victory roar.',
      },
      {
        id: 'star-g7',
        title: 'Roommates Final Pack-Out',
        subtitle: 'Empty Apartment Echoes',
        contributorName: 'Tyler & Chris',
        contributorRole: 'Roommates',
        type: 'photo',
        content: 'Sitting on the carpeted floor of our empty apartment sharing one last cold drink before heading to three different coasts. Brothers for life.',
        mediaUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=80',
        date: 'This Morning',
        likesCount: 48,
        x: 82,
        y: 48,
        size: 'small',
        brightness: 'soft',
        starName: 'Fraternitatis',
        glowColor: '#FF6B6B',
        connections: ['star-g11'],
        quote: 'Sitting on the carpet of our empty flat—brothers for life.',
      },
      {
        id: 'star-g8',
        title: 'Grandfather’s Pocket Watch Gift',
        subtitle: 'Passed Down 3 Generations',
        contributorName: 'Grandpa Walter',
        contributorRole: 'Grandfather',
        type: 'wish',
        content: '“This watch traveled from Poland in 1952. Today it marks the hour our family sees its first aerospace engineer. Go reach for the stars, my boy.”',
        date: 'Today',
        likesCount: 75,
        x: 20,
        y: 78,
        size: 'medium',
        brightness: 'bright',
        starName: 'Horologium Aviti',
        glowColor: '#F59E0B',
        connections: ['star-g9'],
        quote: '“Today this watch marks the hour our family sees its first aerospace engineer.”',
      },
      {
        id: 'star-g9',
        title: 'Speech to the Sophomore Mentorship',
        subtitle: 'Giving Back to Incoming Students',
        contributorName: 'Mentorship Society',
        contributorRole: 'Mentees',
        type: 'wish',
        content: 'Thank you Alex for always keeping your door open, debugging our code without judgment, and inspiring us that anyone can succeed here.',
        date: '2 days ago',
        likesCount: 39,
        x: 42,
        y: 72,
        size: 'small',
        brightness: 'soft',
        starName: 'Lumen Ducis',
        glowColor: '#10B981',
        connections: ['star-g10'],
        quote: '“Thank you for debugging our code and believing in us.”',
      },
      {
        id: 'star-g10',
        title: 'Toast to Future Explorations',
        subtitle: 'Voice Note from Sister Maya',
        contributorName: 'Sister Maya',
        contributorRole: 'Sister',
        type: 'audio',
        duration: '1:02',
        content: '“Alex, you have never settled for the easy road. Whatever rockets you build or skies you explore, know that you’ll always be my hero brother.”',
        mediaUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
        date: 'Yesterday',
        likesCount: 62,
        x: 64,
        y: 70,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Sidera Futura',
        glowColor: '#38BDF8',
        connections: ['star-g11', 'star-g12'],
        quote: '“Whatever rockets you build, know you are my hero brother.”',
      },
      {
        id: 'star-g11',
        title: 'Sunset over Campus Quad',
        subtitle: 'Our Final Walk',
        contributorName: 'Alexander',
        contributorRole: 'Graduate',
        type: 'photo',
        content: 'One last walk past the clock tower and brick arches. Grateful for every friendship forged in these halls.',
        mediaUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
        date: 'Tonight',
        likesCount: 51,
        x: 82,
        y: 76,
        size: 'small',
        brightness: 'soft',
        starName: 'Quadrivium Sol',
        glowColor: '#10B981',
        connections: ['star-g12'],
        quote: 'One last walk past the clock tower, forever grateful.',
      },
      {
        id: 'star-g12',
        title: 'The Sky is Only the Beginning',
        subtitle: 'Blessing from the Faculty',
        contributorName: 'Department of Aerospace Engineering',
        contributorRole: 'Faculty',
        type: 'wish',
        content: 'To Alexander and the Class of 2024: The stars are not the limit; they are merely the laboratory. Go launch your dreams.',
        date: 'Today',
        likesCount: 89,
        x: 52,
        y: 86,
        size: 'medium',
        brightness: 'radiant',
        starName: 'Astra Infinitum',
        glowColor: '#38BDF8',
        connections: ['star-g8'],
        quote: '“The stars are not the limit; they are merely the laboratory.”',
      },
    ],
  },

  Other: {
    occasionType: 'Other',
    personName: 'Our Journey',
    headerTitle: 'Memories in the Sky',
    tagline: 'Every memory is a star in our story.',
    centerpieceTitle: 'OUR STORY',
    centerpieceSubtitle: 'Memories in Orbit',
    centerpieceQuote: '“Moments fade, but memories remain anchored in the stars.”',
    accentColor: '#FF6B6B',
    ambientNebulae: [
      { x: 30, y: 25, color: 'rgba(255, 107, 107, 0.12)', radius: 360, opacity: 0.15 },
      { x: 70, y: 65, color: 'rgba(99, 102, 241, 0.14)', radius: 420, opacity: 0.2 },
    ],
    stars: [], // Handled by fallback to Birthday
  },
};

// Fallback helper to safely retrieve config
export const getConstellationConfig = (type: OccasionType): OccasionConstellationConfig => {
  const config = CONSTELLATION_CONFIGS[type];
  if (config && config.stars.length > 0) return config;
  return CONSTELLATION_CONFIGS.Birthday;
};
